
server:
  port: 9528

spring:
  application:
    name: nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 9e8253e9-4a5d-4d7f-843c-a52936b5d004
        file-extension: yaml
feign:
  hystrix:
    enabled: true